// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package pt.grpc.service.user;

public interface GetUserNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:power.trade.GetUserNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
