// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package pt.grpc.service.user;

public interface GetUserNameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:power.trade.GetUserNameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
