apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  type: ClusterIP
  selector:
    app: grpc-server
  ports:
    - name: web
      port: 8081
      targetPort: 8081
    - name: grpc
      protocol: TCP
      port: 50051
      targetPort: 50051