apiVersion: v1
kind: Service
metadata:
  name: grpc-server
spec:
  type: NodePort
  selector:
    app: grpc-server
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - name: web
      port: 8081
      targetPort: 8081
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30081
    - name: grpc
      port: 50051
      targetPort: 50051
      nodePort: 30051